#Metricfy
version: "2"
services:
  # METRICFY DATABASE SETUP
  metricfy-db-setup:
    image: "node:8"
    container_name: "metricfy-db-setup"
    user: "node"
    working_dir: /home/node/app/metricfy-db
    volumes:
      - /opt/metricfy/source-code:/home/node/app
    env_file:
      - ./env/production.env
    links:
      - metricfy-postgres
    depends_on:
      - metricfy-postgres
    command: "npm run setup-prod"
  # METRICFY MQTT
  metricfy-mqtt:
    image: "node:8"
    restart: always
    container_name: "metricfy-mqtt"
    user: "node"
    working_dir: /home/node/app/metricfy-mqtt
    volumes:
      - /opt/metricfy/source-code:/home/node/app
    ports:
      - "1883:1883"
    env_file:
      - ./env/production.env
    links:
      - metricfy-postgres
      - metricfy-redis
    depends_on:
      - metricfy-postgres
      - metricfy-redis
    command: "npm start"
  # METRICFY API
  metricfy-api:
    image: "node:8"
    restart: always
    container_name: "metricfy-api"
    user: "node"
    working_dir: /home/node/app/metricfy-api
    volumes:
      - /opt/metricfy/source-code:/home/node/app
    ports:
      - "7600:3000"
    env_file:
      - ./env/production.env
    links:
      - metricfy-postgres
    depends_on:
      - metricfy-postgres
    command: "npm start"
  # METRICFY WEB
  metricfy-web:
    image: "node:8"
    restart: always
    container_name: "metricfy-web"
    user: "node"
    working_dir: /home/node/app/metricfy-web
    volumes:
      - /opt/metricfy/source-code:/home/node/app
    ports:
      - "7605:8080"
    env_file:
      - ./env/production.env
    command: "npm start"
  # POSTGRES
  metricfy-postgres:
    image: postgres:9.6
    restart: always
    container_name: "metricfy-postgres"
    env_file:
      - ./env/production.env
    volumes:
      - /opt/metricfy/data/postgres:/var/lib/postgresql/data/pgdata
    ports:
        - 5432:5432
  # redis
  metricfy-redis:
    image: redis:4.0.5-alpine
    container_name: "metricfy-redis"
    restart: always
    command: "redis-server --appendonly yes"
    hostname: redis
    volumes:
      - /opt/metricfy/data/redis:/data